SET NAMES UTF8;
DROP DATABASE IF EXISTS login;
CREATE DATABASE login CHARSET=UTF8;
USE login;
CREATE TABLE users(
uid INT PRIMARY KEY AUTO_INCREMENT,
uname VARCHAR(60),
upwd VARCHAR(60)
);
INSERT INTO users VALUES(null,'sunzhong','123456');